# -*- coding: utf-8 -*-
"""Turkish UI catalog: exact English UI string -> Turkish.

Read at render time by i18n.localize() (installed via i18n.install_localization),
which transparently swaps these in when the language is Turkish. Keys must match the
rendered English string verbatim; anything not listed here falls back to English
(dynamic f-strings, SVG diagram labels, code). Safe to hand-edit — add/adjust entries."""

TR = {
    'Attention — the engine of Transformers & LLMs': "Attention — Transformer'ların ve LLM'lerin motoru",
    'Each token gathers info from the others by dot-product similarity → softmax → weighted sum. Self-attention runs live below on a tiny sentence.': 'Her token, dot-product benzerliği → softmax → ağırlıklı toplam yoluyla diğerlerinden bilgi toplar. Self-attention aşağıda küçük bir cümle üzerinde canlı çalışıyor.',
    '🔎 Live attention': '🔎 Canlı attention',
    '📖 Theory': '📖 Teori',
    '❓ Self-check': '❓ Öz-kontrol',
    '🛠 Tasks': '🛠 Görevler',
    '📚 References': '📚 Kaynaklar',
    'temperature (softmax sharpness)': 'sıcaklık (softmax keskinliği)',
    'inspect query token': "query token'ı incele",
    'Same three pieces you already know: **dot product** (Math X1) for similarity, **softmax** (Math X5) for the weights, then a **weighted sum**.': 'Zaten bildiğin aynı üç parça: benzerlik için **dot product** (Math X1), ağırlıklar için **softmax** (Math X5), sonra bir **ağırlıklı toplam**.',
    'Self-check': 'Öz-kontrol',
    'Instant feedback, no grading.': 'Anında geri bildirim, notlandırma yok.',
    'Tasks': 'Görevler',
    'Reading & references': 'Okuma ve kaynaklar',
    'Attention weights — row = query, column = attended token': 'Attention ağırlıkları — satır = query, sütun = dikkat edilen token',
    'Backprop & autograd': 'Backprop ve autograd',
    "How a network gets a gradient for every weight in one backward pass — run live on the lab's own Value engine (core/engine.py).": 'Bir ağın tek bir geri geçişte (backward pass) her ağırlık için nasıl gradyan elde ettiği — laboratuvarın kendi Value motoru (core/engine.py) üzerinde canlı çalışır.',
    '🔁 Live walkthrough': '🔁 Canlı adım adım',
    'One sigmoid neuron and a squared-error loss: $z=w x+b$, $a=\\sigma(z)$, $L=(a-y)^2$. Move the sliders — the engine recomputes the **forward values** and **back-propagates** the gradients:': "Tek bir sigmoid nöron ve kare-hata loss'u: $z=w x+b$, $a=\\sigma(z)$, $L=(a-y)^2$. Kaydırıcıları oynat — motor **ileri değerleri** yeniden hesaplar ve gradyanları **geri yayar (back-propagate)**:",
    'input x': 'girdi x',
    'weight w': 'ağırlık w',
    'bias b': 'bias b',
    'target y': 'hedef y',
    'output a = σ(z)': 'çıktı a = σ(z)',
    'loss L': 'loss L',
    '∂L/∂w': '∂L/∂w',
    'Take one gradient-descent step (η = 0.5)': 'Bir gradient-descent adımı at (η = 0.5)',
    'Every gradient above is computed by **`core.engine.Value.backward()`** — the same reverse-mode autograd that powers PyTorch, here on scalars.': "Yukarıdaki her gradyan **`core.engine.Value.backward()`** tarafından hesaplanır — PyTorch'u çalıştıran aynı reverse-mode autograd, burada skalerler üzerinde.",
    'CNN — convolutional networks for images': 'CNN — görüntüler için convolutional ağlar',
    'Slide real kernels over an image and watch each become an edge / blur / sharpen detector (a feature map), then pool it — the two ops a CNN stacks.': "Gerçek kernel'ları bir görüntü üzerinde kaydır ve her birinin nasıl bir kenar / bulanıklaştırma / keskinleştirme dedektörüne (feature map) dönüştüğünü gör, sonra pooling uygula — bir CNN'in üst üste dizdiği iki işlem.",
    '🖼 Convolve': '🖼 Convolve',
    'kernel (filter)': 'kernel (filtre)',
    'max-pool 2×2 the result': 'sonuca 2×2 max-pool uygula',
    'image': 'görüntü',
    'kernel': 'kernel',
    '3×3': '3×3',
    'feature map': 'feature map',
    'The 3×3 kernel applied (each output = this filter · the patch under it):': '3×3 kernel uygulandı (her çıktı = bu filtre · altındaki yama):',
    'This is one convolution with one fixed kernel. A CNN stacks **many learned** kernels per layer (channels), interleaves **pooling**, and trains the kernels by backprop — building edges → textures → objects.': "Bu, tek bir sabit kernel ile tek bir convolution. Bir CNN her katmanda **birçok öğrenilen** kernel (kanal) üst üste dizer, araya **pooling** serpiştirir ve kernel'ları backprop ile eğitir — kenarlar → dokular → nesneler kurarak.",
    'Deep nets on 2-D data': '2 boyutlu veride derin ağlar',
    "The MLP idea scaled past XOR — watch a multilayer perceptron bend its boundary to fit moons, rings and spirals (scikit-learn's fast MLP).": "MLP fikrinin XOR'un ötesine ölçeklenmesi — bir multilayer perceptron'ın sınırını ay, halka ve spiralleri uydurmak için nasıl büktüğünü izle (scikit-learn'ün hızlı MLP'si).",
    '🌀 Train it': '🌀 Eğit',
    'dataset': 'veri kümesi',
    'hidden layers': 'gizli katmanlar',
    'activation': 'aktivasyon',
    'seed': 'seed',
    'train accuracy': 'train doğruluğu',
    'test accuracy': 'test doğruluğu',
    "Same MLP idea as the XOR page, scaled to real 2-D data with scikit-learn's vectorized solver. Capacity (width/depth) lets it bend the boundary; too much and it overfits.": "XOR sayfasındaki aynı MLP fikri, scikit-learn'ün vektörleştirilmiş çözücüsüyle gerçek 2 boyutlu veriye ölçeklendi. Kapasite (genişlik/derinlik) sınırı bükmesini sağlar; fazlası overfitting'e yol açar.",
    'Train and test agree — the boundary captures the real shape, not the noise.': 'Train ve test uyuşuyor — sınır gürültüyü değil, gerçek şekli yakalıyor.',
    'Embeddings & RAG — meaning as geometry': 'Embedding ve RAG — geometri olarak anlam',
    'Text → vectors where similar meaning sits nearby (cosine, Math X1); retrieval-augmented generation feeds the most similar facts to the LLM. Live search below.': "Metin → benzer anlamların birbirine yakın durduğu vektörler (cosine, Math X1); retrieval-augmented generation en benzer bilgileri LLM'e verir. Canlı arama aşağıda.",
    '🔎 Retrieve': '🔎 Getir',
    "A tiny **knowledge base** of facts. Ask a question — it's embedded and matched by **cosine similarity**, and the top hits become the LLM's context.": "Küçük bir **bilgi tabanı**. Bir soru sor — embed edilir ve **cosine similarity** ile eşleştirilir; en iyi eşleşmeler LLM'in bağlamı olur.",
    'question': 'soru',
    'top-k': 'top-k',
    'Retrieved facts (ranked by cosine similarity):': "Getirilen bilgiler (cosine similarity'ye göre sıralı):",
    'The prompt RAG would send to the LLM:': "RAG'ın LLM'e göndereceği prompt:",
    'This demo uses lexical TF-IDF vectors, so it matches shared *words*. The pipeline is exactly RAG; real systems swap in **learned semantic** embeddings that also match paraphrases and synonyms.': "Bu demo lexical TF-IDF vektörleri kullanır, yani ortak *kelimeleri* eşleştirir. Pipeline tam olarak RAG'dır; gerçek sistemler bunun yerine, başka ifade biçimlerini ve eş anlamlıları da eşleştiren **öğrenilmiş semantik** embedding'ler kullanır.",
    'the knowledge base (10 facts)': 'bilgi tabanı (10 bilgi)',
    "Top similarity is very low — the answer probably isn't in the knowledge base. A good RAG system says so instead of hallucinating.": 'En yüksek benzerlik çok düşük — cevap muhtemelen bilgi tabanında yok. İyi bir RAG sistemi halüsinasyon görmek yerine bunu söyler.',
    'X2 · Calculus & gradients — playground & lesson': 'X2 · Kalkülüs ve gradyanlar — oyun alanı ve ders',
    'The derivative is the slope of the tangent — the limit of secant slopes as h→0. Shrink h and watch the secant become the tangent.': "Türev, teğetin eğimidir — h→0 giderken kesen (sekant) eğimlerinin limiti. h'yi küçült ve kesenin nasıl teğete dönüştüğünü izle.",
    '🎛 Playground': '🎛 Oyun alanı',
    'f′(x) analytic': 'f′(x) analitik',
    'secant slope': 'kesen eğimi',
    'abs error': 'mutlak hata',
    'As **h → 0** the secant slope converges to the analytic derivative (the error shrinks). That limit *is* the derivative — and the chain rule on it is backprop.': "**h → 0** giderken kesen eğimi analitik türeve yakınsar (hata küçülür). Bu limit türevin *ta kendisidir* — ve üzerindeki chain rule backprop'tur.",
    'function f(x)': 'fonksiyon f(x)',
    'point x': 'nokta x',
    'secant gap h': 'kesen aralığı h',
    'X5 · Information theory — playground & lesson': 'X5 · Bilgi kuramı — oyun alanı ve ders',
    "Cross-entropy is the classification loss. Set the true p and the model's prediction q, and watch cross-entropy bottom out exactly when q = p (KL = 0).": "Cross-entropy, sınıflandırma loss'udur. Gerçek p'yi ve modelin tahmini q'yu ayarla; cross-entropy'nin tam olarak q = p olduğunda (KL = 0) en dibe vurduğunu izle.",
    'entropy H(p)': 'entropi H(p)',
    'cross-entropy H(p,q)': 'cross-entropy H(p,q)',
    'KL(p‖q)': 'KL(p‖q)',
    'Cross-entropy is minimized (= the entropy H(p), so **KL = 0**) exactly when **q = p**. Being confident and wrong (q → 0 while p is high) makes it **explode** — the same behavior that trains classifiers in M2 / ANN.': "Cross-entropy tam olarak **q = p** olduğunda minimize olur (= entropi H(p), yani **KL = 0**). Emin olup yanılmak (p yüksekken q → 0) onu **patlatır** — M2 / ANN'de sınıflandırıcıları eğiten aynı davranış.",
    'true P(class 1)  ·  p': 'gerçek P(sınıf 1)  ·  p',
    'model prediction  ·  q': 'model tahmini  ·  q',
    'X6 · Numerical computing — playground & lesson': 'X6 · Sayısal hesaplama — oyun alanı ve ders',
    "Math on a computer isn't exact. Push the logits up and watch the naive softmax overflow to NaN while the stable (log-sum-exp) version stays correct.": "Bilgisayarda matematik kesin değildir. Logit'leri yukarı it ve naive softmax'ın NaN'a taşarken (overflow) stabil (log-sum-exp) versiyonun nasıl doğru kaldığını izle.",
    'naive softmax': 'naive softmax',
    'stable softmax sums to': 'stabil softmax toplamı',
    "Large logits make naive `exp()` overflow → `inf/inf = NaN`. Subtracting the max first (**log-sum-exp**) keeps it finite — exactly what `core/activations.py`'s stable sigmoid/softmax does.": "Büyük logit'ler naive `exp()`'i taşırır → `inf/inf = NaN`. Önce maksimumu çıkarmak (**log-sum-exp**) onu sonlu tutar — tam olarak `core/activations.py`'deki stabil sigmoid/softmax'ın yaptığı şey.",
    'max logit  M': 'maks logit  M',
    'X4 · Optimization — playground & lesson': 'X4 · Optimizasyon — oyun alanı ve ders',
    'Watch gradient descent roll downhill on f(x,y) = x² + b·y². Push the learning rate until it diverges; raise the anisotropy to see it zig-zag.': "Gradient descent'in f(x,y) = x² + b·y² üzerinde yokuş aşağı yuvarlanmasını izle. Learning rate'i ıraksayana kadar yükselt; zig-zag yapmasını görmek için anizotropiyi artır.",
    'Final loss': 'Son loss',
    'Steps taken': 'Atılan adımlar',
    'Status': 'Durum',
    'Too-large η **overshoots and diverges**; tiny η **crawls**. With b ≫ 1 the bowl becomes a ravine and GD **zig-zags** — which is why feature scaling (M7) and momentum/Adam (§6) matter.': 'Çok büyük η **hedefi aşar ve ıraksar**; çok küçük η **sürünür**. b ≫ 1 olduğunda çanak bir vadiye dönüşür ve GD **zig-zag yapar** — bu yüzden feature scaling (M7) ve momentum/Adam (§6) önemlidir.',
    'learning rate η': 'learning rate η',
    'anisotropy b (ravine)': 'anizotropi b (vadi)',
    'steps': 'adımlar',
    '📐 Mathematical Basics': '📐 Matematik Temelleri',
    'The math you actually need to study ML & ANN — same approach as the other modules: theory + interactive playground + self-check + tasks + references.': 'ML ve ANN çalışmak için gerçekten ihtiyacın olan matematik — diğer modüllerle aynı yaklaşım: teori + etkileşimli oyun alanı + öz-kontrol + görevler + kaynaklar.',
    'The full X1–X6 math basics are built — pick any in the sidebar. X1 (vectors) and X4 (gradient descent) include interactive playgrounds.': "Tüm X1–X6 matematik temelleri hazır — sidebar'dan herhangi birini seç. X1 (vektörler) ve X4 (gradient descent) etkileşimli oyun alanları içerir.",
    'What you need to know': 'Bilmen gerekenler',
    "\n- **X1 — Linear algebra** ✅ — vectors, the **dot product** (interactive), matrices as\n  transformations, norms (L1/L2), projections, a peek at eigenvectors / SVD.\n- **X2 — Calculus** ✅ — derivatives, **partial derivatives**, the **chain rule**,\n  gradients, Jacobians, curvature. *(This is exactly what backpropagation is.)*\n- **X3 — Probability & statistics** ✅ — distributions (esp. the **Gaussian**),\n  expectation & variance, **Bayes' rule**, **maximum likelihood** (= where losses come from).\n- **X4 — Optimization** ✅ — **gradient descent** (interactive), convexity, SGD,\n  learning rate, momentum / Adam.\n- **X5 — Information theory** ✅ — entropy, **cross-entropy**, KL divergence. *(The\n  classification losses of ML/ANN.)*\n- **X6 — Numerical computing** ✅ — floating point, numerical **stability** (log-sum-exp),\n  vectorization, gradient checking.\n\n**Suggested order:** X1 → X2 → X3 → X4, then X5 / X6 as needed.\n": "\n- **X1 — Lineer cebir** ✅ — vektörler, **dot product** (etkileşimli), dönüşüm olarak\n  matrisler, normlar (L1/L2), izdüşümler, eigenvector / SVD'ye kısa bir bakış.\n- **X2 — Kalkülüs** ✅ — türevler, **kısmi türevler**, **chain rule**,\n  gradyanlar, Jacobian'lar, eğrilik. *(Backpropagation tam olarak budur.)*\n- **X3 — Olasılık ve istatistik** ✅ — dağılımlar (özellikle **Gaussian**),\n  beklenen değer ve varyans, **Bayes kuralı**, **maximum likelihood** (= loss'ların kaynağı).\n- **X4 — Optimizasyon** ✅ — **gradient descent** (etkileşimli), dışbükeylik, SGD,\n  learning rate, momentum / Adam.\n- **X5 — Bilgi kuramı** ✅ — entropi, **cross-entropy**, KL diverjansı. *(ML/ANN'in\n  sınıflandırma loss'ları.)*\n- **X6 — Sayısal hesaplama** ✅ — kayan nokta (floating point), sayısal **stabilite** (log-sum-exp),\n  vektörleştirme, gradient checking.\n\n**Önerilen sıra:** X1 → X2 → X3 → X4, ardından gerektikçe X5 / X6.\n",
    'How the math powers the other modules': 'Matematik diğer modülleri nasıl güçlendiriyor',
    "\n| math topic | shows up as |\n|---|---|\n| dot product (X1) | a neuron's pre-activation $z=\\mathbf w\\cdot\\mathbf x+b$ |\n| matrix multiply (X1) | a whole layer $W\\mathbf x+\\mathbf b$ |\n| chain rule (X2) | backpropagation (ANN Tier 1) |\n| gradient descent (X4) | how every model learns |\n| cross-entropy (X5) | the classification loss (ML & ANN) |\n| Gaussian / MLE (X3) | why squared error = linear regression |\n\nSwitch modules anytime with the selector at the top of the sidebar.\n": "\n| matematik konusu | şu şekilde karşına çıkar |\n|---|---|\n| dot product (X1) | bir nöronun pre-activation'ı $z=\\mathbf w\\cdot\\mathbf x+b$ |\n| matris çarpımı (X1) | tüm bir katman $W\\mathbf x+\\mathbf b$ |\n| chain rule (X2) | backpropagation (ANN Tier 1) |\n| gradient descent (X4) | her modelin nasıl öğrendiği |\n| cross-entropy (X5) | sınıflandırma loss'u (ML ve ANN) |\n| Gaussian / MLE (X3) | neden kare hata = linear regression |\n\nModülleri istediğin zaman sidebar'ın üstündeki seçiciyle değiştir.\n",
    'X3 · Probability — playground & lesson': 'X3 · Olasılık — oyun alanı ve ders',
    "Explore the key distributions (shape, mean, variance, where they're used), or watch the Central Limit Theorem turn any distribution's average into a Gaussian.": "Temel dağılımları keşfet (şekil, ortalama, varyans, nerede kullanıldıkları) ya da Merkezi Limit Teoremi'nin herhangi bir dağılımın ortalamasını nasıl Gaussian'a dönüştürdüğünü izle.",
    'mean': 'ortalama',
    'variance': 'varyans',
    'std': 'std',
    'n (averaged)': 'n (ortalanan)',
    'mean of means': 'ortalamaların ortalaması',
    'std of means': "ortalamaların std'si",
    "At **n = 1** you see the base distribution's true (often skewed) shape. As **n grows**, the average becomes **Gaussian** (CLT) and its spread shrinks ~1/√n.": '**n = 1** iken temel dağılımın gerçek (çoğu zaman çarpık) şeklini görürsün. **n büyüdükçe** ortalama **Gaussian** olur (CLT) ve yayılımı ~1/√n oranında küçülür.',
    'playground': 'oyun alanı',
    'distribution': 'dağılım',
    'base distribution (not Gaussian!)': 'temel dağılım (Gaussian değil!)',
    'sample size n (averaged)': 'örneklem boyutu n (ortalanan)',
    'λ (rate)': 'λ (oran)',
    'μ (mean)': 'μ (ortalama)',
    'σ (std)': 'σ (std)',
    'shape α': 'şekil α',
    'rate β': 'oran β',
    'Vectors & the dot product — playground & lesson': 'Vektörler ve dot product — oyun alanı ve ders',
    "X1 · w·x is a neuron's pre-activation. Drag two vectors and watch the dot product, angle, and projection.": "X1 · w·x bir nöronun pre-activation'ıdır. İki vektörü sürükle ve dot product'ı, açıyı ve izdüşümü izle.",
    'w · x': 'w · x',
    'angle θ': 'açı θ',
    'cos θ': 'cos θ',
    'proj of x on w': "x'in w üzerine izdüşümü",
    "This is exactly a neuron's pre-activation z = w·x (the bias just shifts it). Maximum when x points the same way as w (θ=0°); zero when perpendicular (θ=90°); negative when opposed.": "Bu tam olarak bir nöronun pre-activation'ı z = w·x (bias sadece onu kaydırır). x, w ile aynı yöne işaret ettiğinde maksimum (θ=0°); dik olduğunda sıfır (θ=90°); zıt olduğunda negatif.",
    '**Vector w**': '**Vektör w**',
    'w₁': 'w₁',
    'w₂': 'w₂',
    '**Vector x**': '**Vektör x**',
    'x₁': 'x₁',
    'x₂': 'x₂',
    'M2 · Classification — playground & lesson': 'M2 · Sınıflandırma — oyun alanı ve ders',
    'Logistic regression = a sigmoid neuron. Move the threshold and watch the confusion matrix and precision/recall trade off.': 'Logistic regression = bir sigmoid nöron. Eşiği (threshold) oynat ve confusion matrix ile precision/recall arasındaki dengeyi izle.',
    'Accuracy': 'Doğruluk',
    'Precision': 'Precision',
    'Recall': 'Recall',
    'F1': 'F1',
    '**Confusion matrix**': '**Confusion matrix**',
    'Lower the threshold → more points called **class 1** → recall ↑, precision ↓ (a spam filter wants high precision; a cancer screen wants high recall).': 'Eşiği düşür → daha çok nokta **sınıf 1** sayılır → recall ↑, precision ↓ (bir spam filtresi yüksek precision ister; bir kanser taraması yüksek recall ister).',
    'points per class': 'sınıf başına nokta',
    'class separation': 'sınıf ayrımı',
    'spread / overlap (σ)': 'yayılım / örtüşme (σ)',
    'decision threshold': 'karar eşiği',
    'M0 · Foundations — playground & lesson': 'M0 · Temeller — oyun alanı ve ders',
    "The core idea of ML: generalize, don't memorize. Crank model complexity and watch underfitting turn into overfitting.": "ML'in temel fikri: ezberleme, genelle. Model karmaşıklığını yükselt ve underfitting'in nasıl overfitting'e dönüştüğünü izle.",
    'Degree': 'Derece',
    'Train MSE': 'Train MSE',
    'Test MSE': 'Test MSE',
    '**Low degree → underfit** (high train *and* test error). **High degree → overfit** (tiny train error, large test error — it memorized noise). The best model **minimizes test error**.': '**Düşük derece → underfit** (hem train *hem* test hatası yüksek). **Yüksek derece → overfit** (çok küçük train hatası, büyük test hatası — gürültüyü ezberledi). En iyi model **test hatasını minimize eder**.',
    'data points': 'veri noktaları',
    'noise σ': 'gürültü σ',
    'model complexity (polynomial degree)': 'model karmaşıklığı (polinom derecesi)',
    'train fraction': 'train oranı',
    'M6 · Model selection — playground & lesson': 'M6 · Model seçimi — oyun alanı ve ders',
    'Pick the model that wins on held-out data, not on training data. The validation curve (via k-fold CV) shows train error always falling while CV error is U-shaped.': 'Train verisinde değil, ayrılmış (held-out) veride kazanan modeli seç. Validation eğrisi (k-fold CV ile) train hatasının hep düştüğünü, CV hatasının ise U şeklinde olduğunu gösterir.',
    'Best degree (by CV)': "En iyi derece (CV'ye göre)",
    'CV MSE @ best': 'En iyideki CV MSE',
    'Train MSE @ best': 'En iyideki Train MSE',
    '**Train MSE keeps falling** as the model gets more flexible (it can always fit training data better) — so choosing by train error would always pick the most complex model. **CV MSE is U-shaped**; its minimum is the model that generalizes best. *That* is model selection.': 'Model esnekleştikçe **Train MSE düşmeye devam eder** (train verisini her zaman daha iyi uydurabilir) — bu yüzden train hatasına göre seçim hep en karmaşık modeli seçer. **CV MSE U şeklindedir**; minimumu en iyi genelleyen modeldir. Model seçimi *işte budur*.',
    'CV folds (k)': 'CV fold sayısı (k)',
    'max polynomial degree': 'maks polinom derecesi',
    '🧮 Machine Learning': '🧮 Makine Öğrenmesi',
    'Classical ML — same approach as the ANN module: theory + interactive playground + self-check + tasks + references, one topic at a time.': 'Klasik ML — ANN modülüyle aynı yaklaşım: teori + etkileşimli oyun alanı + öz-kontrol + görevler + kaynaklar, her seferinde tek konu.',
    '📚 ML roadmap — foundations → doing it for real': '📚 ML yol haritası — temellerden gerçek uygulamaya',
    'Five levels, **basics to practice** — work top to bottom; **click any step to open it**. This is the **ML track**; the **ANN** track (single neuron → GPT) and the **Math (X1–X6)** foundations are in the sidebar **Module** selector. Every module below has an interactive playground (M7 is reference).': "Beş seviye, **temellerden pratiğe** — yukarıdan aşağı ilerle; **her adıma tıklayarak açabilirsin**. Bu **ML kanalı**; **ANN** kanalı (tek nörondan GPT'ye) ve **Math (X1–X6)** temelleri sidebar'daki **Modül** seçicide. Aşağıdaki her modülün etkileşimli bir oyun alanı var (M7 referanstır).",
    'Where ML meets ANN': 'ML ve ANN nerede buluşuyor',
    '\nThe two tracks are not separate worlds — they meet at the **single neuron**:\n\n| single neuron | + loss | = classical model |\n|---|---|---|\n| linear activation | MSE | **linear regression** (M1) |\n| sigmoid activation | cross-entropy | **logistic regression** (M2) |\n\nSo everything you learn about weights, bias, and activations in the **ANN** module pays off\ndirectly here — and vice-versa. Switch tracks anytime with the **Module** selector at the top\nof the sidebar.\n': "\nİki kanal ayrı dünyalar değil — **tek nöronda** buluşurlar:\n\n| tek nöron | + loss | = klasik model |\n|---|---|---|\n| lineer aktivasyon | MSE | **linear regression** (M1) |\n| sigmoid aktivasyon | cross-entropy | **logistic regression** (M2) |\n\nYani **ANN** modülünde ağırlıklar, bias ve aktivasyonlar hakkında öğrendiğin her şey\nburada doğrudan işe yarar — ve tam tersi. Kanalları istediğin zaman sidebar'ın üstündeki\n**Modül** seçiciyle değiştir.\n",
    'M7 · Practical ML': 'M7 · Pratik ML',
    'The craft that decides whether a project works: features, scaling, leakage, pipelines.': "Bir projenin işe yarayıp yaramayacağını belirleyen zanaat: feature'lar, scaling, leakage, pipeline'lar.",
    'ML in Python — the practical toolkit': 'Python ile ML — pratik araç seti',
    'M8 · How classical ML is actually done in Python (NumPy · pandas · scikit-learn). The examples below really run — scikit-learn trains them in-page.': "M8 · Klasik ML'in Python'da gerçekte nasıl yapıldığı (NumPy · pandas · scikit-learn). Aşağıdaki örnekler gerçekten çalışır — scikit-learn onları sayfa içinde eğitir.",
    '🧪 Live examples': '🧪 Canlı örnekler',
    '1 · Classification, end to end': '1 · Sınıflandırma, baştan sona',
    'Pick a built-in dataset and a model — it splits, scales, trains and scores live.': 'Hazır bir veri kümesi ve bir model seç — canlı olarak böler, ölçekler, eğitir ve skorlar.',
    'Dataset': 'Veri kümesi',
    'Model': 'Model',
    'Test accuracy': 'Test doğruluğu',
    '5-fold CV': '5-fold CV',
    'Data': 'Veri',
    'The exact code that just ran:': 'Az önce çalışan kodun tamamı:',
    "Swap the **Model** dropdown and only the constructor line changes — that's the scikit-learn API: `fit` / `predict` / `score` for every model.": "**Model** açılır menüsünü değiştir — yalnızca constructor satırı değişir. scikit-learn API'si budur: her model için `fit` / `predict` / `score`.",
    '2 · Regression — comparing models by cross-validation': '2 · Regresyon — modelleri cross-validation ile karşılaştırma',
    'Three regressors on the diabetes dataset, scored by 5-fold CV R² (higher is better).': 'Diabetes veri kümesinde üç regresör, 5-fold CV R² ile skorlandı (yüksek olan daha iyi).',
    'Same `cross_val_score` call, three models — swapping estimators is one line each.': 'Aynı `cross_val_score` çağrısı, üç model — estimator değiştirmek her biri için tek satır.',
    'Confusion matrix (rows = true, cols = predicted)': 'Confusion matrix (satırlar = gerçek, sütunlar = tahmin)',
    'Classification report (per class)': 'Sınıflandırma raporu (sınıf bazında)',
    'Linear regression — playground & lesson': 'Linear regression — oyun alanı ve ders',
    'M1 · ŷ = w·x + b.  Fit a line to data by hand, then let least squares do it perfectly.': "M1 · ŷ = w·x + b.  Veriye elle bir doğru uydur, sonra least squares'in bunu kusursuz yapmasına izin ver.",
    'Your MSE': "Senin MSE'n",
    'Best MSE (OLS)': 'En iyi MSE (OLS)',
    'Your R²': "Senin R²'n",
    'Minimize **Your MSE** by hand, then press **Fit** to jump to the optimum. Open **Theory** for why least squares is that optimum.': "**Senin MSE'ni** elle minimize et, sonra optimuma atlamak için **Fit**'e bas. Least squares'in neden o optimum olduğunu görmek için **Teori**'yi aç.",
    '**Data**': '**Veri**',
    'points': 'nokta',
    'true slope': 'gerçek eğim',
    'true intercept': 'gerçek kesişim',
    '**Your model**': '**Senin modelin**',
    'w (slope)': 'w (eğim)',
    'b (intercept)': 'b (kesişim)',
    'show residuals': 'artıkları (residual) göster',
    'Fit (least squares)': 'Fit (least squares)',
    'M4 · SVM & kernels — playground & lesson': 'M4 · SVM ve kernel — oyun alanı ve ders',
    'A linear kernel draws a straight margin; the RBF kernel bends it. Try the linear kernel on XOR (it fails) then switch to RBF (it works).': "Lineer kernel düz bir margin çizer; RBF kernel onu büker. XOR üzerinde lineer kernel'ı dene (başarısız olur), sonra RBF'ye geç (işe yarar).",
    'Train accuracy': 'Train doğruluğu',
    'Support vectors': "Support vector'ler",
    'Kernel': 'Kernel',
    "**Linear** kernel on **XOR** can't separate the classes (~50–75%). Switch to **RBF** and it bends the boundary to fit. **C** trades margin width vs. errors; **γ** sets how local the RBF boundary is (large γ → wiggly/overfit).": "**XOR** üzerinde **lineer** kernel sınıfları ayıramaz (~%50–75). **RBF**'ye geç; sınırı uyacak şekilde büker. **C**, margin genişliği ile hatalar arasında denge kurar; **γ**, RBF sınırının ne kadar yerel olduğunu belirler (büyük γ → dalgalı/overfit).",
    'C (less ↔ more regularization)': 'C (az ↔ çok regularizasyon)',
    'γ (RBF reach)': 'γ (RBF erişimi)',
    'M3 · Trees & ensembles — playground & lesson': 'M3 · Ağaçlar ve ensemble — oyun alanı ve ders',
    'A decision tree carves space with axis-aligned splits. Raise the depth and watch it go from underfit → good → overfit (train ↑, test ↓).': 'Bir decision tree, uzayı eksene hizalı bölmelerle parçalar. Derinliği artır ve underfit → iyi → overfit gidişini izle (train ↑, test ↓).',
    'Depth': 'Derinlik',
    'Depth 1–2 **underfits** the checkerboard; a few levels capture it; very deep **overfits** the noise — train accuracy keeps climbing while test accuracy falls. An ensemble (random forest) would stabilize this.': 'Derinlik 1–2 dama tahtasını **underfit eder**; birkaç seviye onu yakalar; çok derin olan gürültüyü **overfit eder** — train doğruluğu tırmanmaya devam ederken test doğruluğu düşer. Bir ensemble (random forest) bunu dengelerdi.',
    'label noise': 'etiket gürültüsü',
    'max tree depth': 'maks ağaç derinliği',
    'M5 · Unsupervised — playground & lesson': 'M5 · Denetimsiz öğrenme — oyun alanı ve ders',
    'No labels — find structure. Watch k-means group points and place centroids; try the wrong k and see the inertia change.': "Etiket yok — yapıyı bul. k-means'in noktaları gruplayıp centroid'leri yerleştirmesini izle; yanlış k'yı dene ve inertia'nın nasıl değiştiğini gör.",
    'k (chosen)': 'k (seçilen)',
    'true clusters': 'gerçek kümeler',
    'inertia': 'inertia',
    "Inertia always **drops as k rises** (more centroids), so you can't just minimize it — use the **elbow** or **silhouette** to choose k. Try k below/above the true number and change the seed to see init sensitivity.": "Inertia, **k arttıkça hep düşer** (daha çok centroid), bu yüzden onu basitçe minimize edemezsin — k'yı seçmek için **dirsek (elbow)** ya da **silhouette** kullan. Gerçek sayının altında/üstünde k'yı dene ve init duyarlılığını görmek için seed'i değiştir.",
    'points per true cluster': 'gerçek küme başına nokta',
    'true clusters in the data': 'verideki gerçek kümeler',
    'spread (overlap)': 'yayılım (örtüşme)',
    'k (clusters to find)': 'k (bulunacak küme sayısı)',
    'MLP — train a whole network': 'MLP — bütün bir ağı eğit',
    "Stack neurons into a hidden layer and a multilayer perceptron learns XOR — trained live on the lab's Value MLP + optimizer (core/nn.py, core/optim.py).": "Nöronları bir gizli katmanda üst üste diz; bir multilayer perceptron XOR'u öğrenir — laboratuvarın Value MLP'si + optimizer'ı (core/nn.py, core/optim.py) üzerinde canlı eğitilir.",
    '🏋 Train it': '🏋 Eğit',
    'A 2-input MLP with one hidden layer learns **XOR** (targets ±1, tanh output, predict by sign). Tune the network and watch it train:': "Bir gizli katmanlı, 2 girdili bir MLP **XOR**'u öğrenir (hedefler ±1, tanh çıktı, işarete göre tahmin). Ağı ayarla ve eğitilişini izle:",
    'optimizer': 'optimizer',
    'random seed (initial weights)': 'rastgele seed (başlangıç ağırlıkları)',
    'final loss': 'son loss',
    'XOR solved': 'XOR çözüldü',
    'parameters': 'parametreler',
    'This is the real training loop on `core.nn.MLP` + `core.optim` — forward → MSE → `loss.backward()` → `opt.step()`, repeated each epoch.': "Bu, `core.nn.MLP` + `core.optim` üzerindeki gerçek eğitim döngüsü — ileri (forward) → MSE → `loss.backward()` → `opt.step()`, her epoch'ta tekrarlanır.",
    'Loss over training': 'Eğitim boyunca loss',
    'Learned decision boundary': 'Öğrenilen karar sınırı',
    '4/4 — the hidden layer bent input space until XOR became separable. What one neuron (Two neurons page / e03) could never do.': '4/4 — gizli katman, XOR ayrılabilir hale gelene kadar girdi uzayını büktü. Tek bir nöronun (İki nöron sayfası / e03) asla yapamadığı şey.',
    'Neurons → a computer': 'Nöronlar → bir bilgisayar',
    'A single neuron is a logic gate. Wire gates together and neurons do arithmetic — and, since NAND alone is universal, in principle ANY computation.': 'Tek bir nöron bir mantık kapısıdır. Kapıları birbirine bağla; nöronlar aritmetik yapar — ve tek başına NAND evrensel olduğu için, ilkesel olarak HERHANGİ bir hesaplama.',
    "**Step 1 — a neuron is a gate.** Each of these is *one* TLU neuron `y = step(w·x − θ)`:\n\n| gate | weights w | threshold θ |\n|---|---|---|\n| AND | [1, 1] | 1.5 |\n| OR | [1, 1] | 0.5 |\n| NAND | [−1, −1] | −1.5 |\n| NOT | [−1] | −0.5 |\n\nXOR isn't linearly separable, so it takes **two** neurons (a hidden AND + an output) — exactly the *Two neurons* page.": '**Adım 1 — bir nöron bir kapıdır.** Bunların her biri *tek* bir TLU nöronudur `y = step(w·x − θ)`:\n\n| kapı | ağırlıklar w | eşik θ |\n|---|---|---|\n| AND | [1, 1] | 1.5 |\n| OR | [1, 1] | 0.5 |\n| NAND | [−1, −1] | −1.5 |\n| NOT | [−1] | −0.5 |\n\nXOR lineer olarak ayrılabilir değildir, bu yüzden **iki** nöron gerekir (gizli bir AND + bir çıktı) — tam olarak *İki nöron* sayfası.',
    'Step 2 — wire gates into an adder (neurons doing arithmetic)': 'Adım 2 — kapıları bir toplayıcıya (adder) bağla (aritmetik yapan nöronlar)',
    "To **add two bits** you need two answers: the **Sum** bit and the **Carry** bit. Look at `1 + 1`: the answer is `2`, which in binary is `10` — Sum = 0, Carry = 1. That's exactly **Sum = XOR(A,B)** and **Carry = AND(A,B)** — two neurons, the *half adder* below.": "**İki bit'i toplamak** için iki cevap gerekir: **Sum** (toplam) bit'i ve **Carry** (elde) bit'i. `1 + 1`'e bak: cevap `2`, ikili tabanda `10` — Sum = 0, Carry = 1. Bu tam olarak **Sum = XOR(A,B)** ve **Carry = AND(A,B)** — iki nöron, aşağıdaki *yarım toplayıcı (half adder)*.",
    "Step 3 — why this means 'any computation'": "Adım 3 — bu neden 'herhangi bir hesaplama' anlamına geliyor",
    "- A neuron can be a **NAND** gate, and **NAND is functionally complete** — every logic circuit can be built from NANDs alone.\n- So networks of neurons can compute **any boolean function**, and (with memory / feedback) anything a computer can.\n- A real **trained** network does the same thing with **soft, learned gates** (sigmoids instead of hard steps) and weights found by **gradient descent** instead of hand-set — that's the only real difference between this adder and a deep net.\n- And physically it's all one operation, repeated: **weighted sums (matrix multiplies) + a nonlinearity**.": "- Bir nöron **NAND** kapısı olabilir ve **NAND fonksiyonel olarak tamdır** — her mantık devresi yalnızca NAND'lerden kurulabilir.\n- Yani nöron ağları **herhangi bir boolean fonksiyonunu** hesaplayabilir ve (bellek / geri besleme ile) bir bilgisayarın yapabildiği her şeyi.\n- Gerçek bir **eğitilmiş** ağ aynı şeyi **yumuşak, öğrenilmiş kapılarla** (sert adımlar yerine sigmoid'ler) ve elle ayarlanmak yerine **gradient descent** ile bulunan ağırlıklarla yapar — bu toplayıcı ile derin bir ağ arasındaki tek gerçek fark budur.\n- Ve fiziksel olarak hepsi tek bir işlemin tekrarıdır: **ağırlıklı toplamlar (matris çarpımları) + bir nonlinearity**.",
    'Logic circuits, in 60 seconds': 'Mantık devreleri, 60 saniyede',
    "The very same *neuron = gate* idea scales all the way up to a real computer. Five rungs on the ladder:\n\n1. **Gates** — AND, OR, NOT, NAND. Each is one neuron (XOR needs two). The alphabet.\n2. **Combinational logic** — wire gates together with **no loops** so outputs depend only on the current inputs: **adders** (above), **multiplexers** (pick one of several inputs), **decoders**, comparators. This is *arithmetic and choosing*.\n3. **Memory** — now add a **feedback loop**: route an output back into the input, and a pair of gates can **hold a bit** (a *latch* / flip-flop). Loops give you **state** — something a plain feed-forward network simply does not have.\n4. **Sequential logic** — gates + memory + a **clock** that ticks. The machine now has *steps*: registers, counters, state machines — it can follow a procedure.\n5. **A CPU** is just a vast pile of exactly these — gates for the arithmetic unit, latches for registers and RAM, and control logic sequencing it all. Same Lego bricks, billions of them.\n\nSo the whole arc is: **neuron → gate → circuit → (＋ feedback) memory → (＋ a clock) a programmable computer.** The jump that matters is the **feedback loop** — that's what turns a calculator into a computer.": "Aynı *nöron = kapı* fikri ta gerçek bir bilgisayara kadar ölçeklenir. Merdivende beş basamak:\n\n1. **Kapılar** — AND, OR, NOT, NAND. Her biri bir nörondur (XOR iki ister). Alfabe.\n2. **Kombinasyonel mantık** — kapıları **döngüsüz** bağla, böylece çıktılar yalnızca mevcut girdilere bağlı olsun: **toplayıcılar (adder)** (yukarıda), **multiplexer'lar** (birkaç girdiden birini seçer), **decoder'lar**, karşılaştırıcılar. Bu, *aritmetik ve seçme*.\n3. **Bellek** — şimdi bir **geri besleme döngüsü** ekle: bir çıktıyı tekrar girdiye yönlendir; bir çift kapı **bir bit tutabilir** (*latch* / flip-flop). Döngüler sana **durum (state)** verir — sade bir feed-forward ağında olmayan bir şey.\n4. **Ardışıl (sequential) mantık** — kapılar + bellek + tik taklayan bir **saat (clock)**. Makinenin artık *adımları* var: register'lar, sayaçlar, durum makineleri — bir prosedürü izleyebilir.\n5. **Bir CPU** tam olarak bunların devasa bir yığınıdır — aritmetik birim için kapılar, register'lar ve RAM için latch'ler ve hepsini sıralayan kontrol mantığı. Aynı Lego parçaları, milyarlarcası.\n\nYani tüm yay şudur: **nöron → kapı → devre → (＋ geri besleme) bellek → (＋ bir saat) programlanabilir bir bilgisayar.** Asıl önemli sıçrama **geri besleme döngüsüdür** — bir hesap makinesini bilgisayara dönüştüren şey budur.",
    'Is an ANN model really a computer?': 'Bir ANN modeli gerçekten bir bilgisayar mı?',
    "Short answer: a standard **feed-forward** neural network is **not** a general-purpose computer — it's a fixed **function**. But the line is subtle and worth drawing carefully.": 'Kısa cevap: standart bir **feed-forward** sinir ağı genel amaçlı bir bilgisayar **değildir** — sabit bir **fonksiyondur**. Ama bu sınır incedir ve dikkatle çizilmeye değer.',
    "**The honest takeaway.** A neuron is a (soft) **logic gate**; a network is a **circuit**; a *trained* network is a circuit whose gates were **learned from data** instead of wired by an engineer. That makes it a **universal function approximator** — and, *with feedback and memory*, a genuine computer. The deep difference from your laptop's CPU isn't the ingredients (it's all gates and memory either way) — it's that the network's 'program' is **learned weights**: fuzzy, statistical, and robust, rather than exact hand-written instructions.": "**Dürüst sonuç.** Bir nöron (yumuşak) bir **mantık kapısıdır**; bir ağ bir **devredir**; *eğitilmiş* bir ağ, kapıları bir mühendis tarafından bağlanmak yerine **veriden öğrenilmiş** bir devredir. Bu onu bir **evrensel fonksiyon yaklaştırıcısı (universal function approximator)** yapar — ve *geri besleme ve bellekle* gerçek bir bilgisayar. Dizüstündeki CPU'dan asıl derin fark malzemeler değildir (her iki durumda da hepsi kapı ve bellektir) — farklı olan, ağın 'programının' **öğrenilmiş ağırlıklar** olmasıdır: kesin, elle yazılmış komutlar yerine bulanık, istatistiksel ve dayanıklı.",
    'Rule of thumb: **depth → a better function; feedback → a computer.** Our adder is a circuit; an LLM borrows loops and memory to act like a computer.': 'Pratik kural: **derinlik → daha iyi bir fonksiyon; geri besleme → bir bilgisayar.** Toplayıcımız bir devredir; bir LLM, bir bilgisayar gibi davranmak için döngüleri ve belleği ödünç alır.',
    'Circuit': 'Devre',
    'A + B (decimal)': 'A + B (ondalık)',
    'Carry': 'Carry (elde)',
    'Sum': 'Sum (toplam)',
    "Built from **2 neurons**: Carry = AND(A,B), Sum = XOR(A,B). Tick both A and B: Carry=1, Sum=0 — that's binary **10 = 2**. The neurons added 1+1.": "**2 nörondan** kurulu: Carry = AND(A,B), Sum = XOR(A,B). Hem A'yı hem B'yi işaretle: Carry=1, Sum=0 — bu ikili tabanda **10 = 2**. Nöronlar 1+1'i topladı.",
    'A + B + Cin': 'A + B + Cin',
    'Carry-out': 'Carry-out (taşıma)',
    "A full adder = two half-adders + an OR. Chain n of these and neurons add n-bit numbers — the core of a CPU's arithmetic unit.": "Tam toplayıcı (full adder) = iki yarım toplayıcı + bir OR. Bunlardan n tanesini zincirle; nöronlar n-bit'lik sayıları toplar — bir CPU'nun aritmetik biriminin çekirdeği.",
    'What a plain MLP actually is': 'Sade bir MLP aslında nedir',
    "Once trained, a feed-forward net maps **inputs → outputs in a fixed number of steps**, with **no loops** and **no writable memory**. It *can* compute any boolean function (we just built arithmetic) and approximate any continuous function — so it is **universal as a function**. But it cannot 'loop until done', cannot store and recall arbitrary data, cannot take an unbounded number of steps. So an MLP is much more like **one big combinational circuit** than like a computer.": "Bir kez eğitildikten sonra, bir feed-forward ağ **girdileri → çıktılara sabit sayıda adımda** eşler; **döngü yok** ve **yazılabilir bellek yok**. Herhangi bir boolean fonksiyonunu hesaplayabilir (az önce aritmetik kurduk) ve herhangi bir sürekli fonksiyonu yaklaştırabilir — yani **bir fonksiyon olarak evrenseldir**. Ama 'bitene kadar döngü' kuramaz, rastgele veriyi saklayıp geri çağıramaz, sınırsız sayıda adım atamaz. Yani bir MLP, bir bilgisayardan çok **tek bir büyük kombinasyonel devreye** benzer.",
    'What makes something a computer': 'Bir şeyi bilgisayar yapan nedir',
    'Three ingredients a plain MLP lacks:\n- **Memory** — writable, readable state.\n- **Control flow** — loops/branches that run a *variable* number of steps.\n- **Programmability** — behaviour you can change without rebuilding the hardware.\n\nCrucially, these come from **feedback/recurrence**, *not* from depth. Stacking more layers makes a richer function; it does **not** by itself make a computer.': "Sade bir MLP'de olmayan üç bileşen:\n- **Bellek** — yazılabilir, okunabilir durum.\n- **Kontrol akışı** — *değişken* sayıda adım çalışan döngüler/dallanmalar.\n- **Programlanabilirlik** — donanımı yeniden kurmadan değiştirebileceğin davranış.\n\nÖnemlisi, bunlar derinlikten *değil*, **geri besleme/özyineleme (recurrence)**'den gelir. Daha çok katman üst üste koymak daha zengin bir fonksiyon yapar; tek başına bir bilgisayar **yapmaz**.",
    'Where neural nets cross the line': 'Sinir ağları sınırı nerede aşıyor',
    "- **Recurrent nets (RNN / LSTM)** add feedback = memory over time. In theory, an RNN with enough precision is **Turing-complete** — it *can* express general computation.\n- **Transformers / LLMs** are feed-forward per step, but run **autoregressively** (feed each output back in as input) and can use a **scratchpad** ('chain of thought') and external **tools**. That effectively buys them loops and memory — which is why an LLM can carry out genuine multi-step procedures.": "- **Recurrent ağlar (RNN / LSTM)** geri besleme ekler = zaman içinde bellek. Teoride, yeterli hassasiyete sahip bir RNN **Turing-complete**'tir — genel hesaplamayı ifade *edebilir*.\n- **Transformer'lar / LLM'ler** adım başına feed-forward'dur ama **autoregressive** çalışır (her çıktıyı tekrar girdi olarak besler) ve bir **karalama defteri** ('chain of thought') ile harici **araçlar** kullanabilir. Bu, onlara fiilen döngü ve bellek kazandırır — bir LLM'in gerçek çok adımlı prosedürleri bu yüzden yürütebilmesinin nedeni budur.",
    'A = 1': 'A = 1',
    'B = 1': 'B = 1',
    'Cin = 1': 'Cin = 1',
    'Optimizers compared — SGD · Momentum · Adam': "Optimizer'lar karşılaştırıldı — SGD · Momentum · Adam",
    "The same ravine, three optimizers, run on the lab's core.optim. Watch how each handles a surface that's steep one way and flat the other.": "Aynı vadi, üç optimizer, laboratuvarın core.optim'i üzerinde çalışıyor. Her birinin, bir yönde dik diğer yönde düz bir yüzeyle nasıl başa çıktığını izle.",
    '🏁 Compare': '🏁 Karşılaştır',
    'Minimizing the **ravine** $f(x,y) = A\\,x^2 + y^2$ (steep in $x$, flat in $y$) from the same start. Tune the shared learning rate and the steepness:': "Aynı başlangıçtan **vadiyi** $f(x,y) = A\\,x^2 + y^2$ minimize etme ($x$'te dik, $y$'de düz). Ortak learning rate'i ve dikliği ayarla:",
    "All three are the lab's `core.optim` (SGD/Momentum/Adam) stepping on gradients from `core.engine.Value.backward()`. Same η: SGD zig-zags down the steep axis, Momentum rolls through, Adam adapts per-axis.": "Üçü de laboratuvarın `core.optim`'i (SGD/Momentum/Adam) ve `core.engine.Value.backward()`'dan gelen gradyanlar üzerinde adım atar. Aynı η: SGD dik eksende zig-zag yapar, Momentum yuvarlanıp geçer, Adam eksen bazında uyarlanır.",
    'Paths over the loss contours': 'Loss konturları üzerindeki yollar',
    'Loss vs step (log scale)': "Loss'a karşı adım (log ölçek)",
    'Neuron — playground & lesson': 'Nöron — oyun alanı ve ders',
    'e01 · a = φ(w·x + b).  One neuron, n inputs. Experiment, then learn the theory, test yourself, and practice.': 'e01 · a = φ(w·x + b).  Bir nöron, n girdi. Deneyle, sonra teoriyi öğren, kendini test et ve pratik yap.',
    'Truth table': 'Doğruluk tablosu',
    'Instant feedback, no grading. Use it to find the gaps.': 'Anında geri bildirim, notlandırma yok. Eksikleri bulmak için kullan.',
    'Inputs (n)': 'Girdiler (n)',
    'activation φ': 'aktivasyon φ',
    'bias': 'bias',
    'One input → the plot is the full response curve a(x₀); the dashed line is the threshold z=0.': 'Tek girdi → grafik, tam tepki eğrisi a(x₀); kesikli çizgi z=0 eşiğidir.',
    'Run a starter in the 🐍 Sandbox (numpy + core preloaded):': "🐍 Sandbox'ta bir başlangıç kodu çalıştır (numpy + core önceden yüklü):",
    'Try: single neuron →': 'Dene: tek nöron →',
    'Try: perceptron rule →': 'Dene: perceptron kuralı →',
    'Drag **only the bias** from the AND preset toward −0.5 and watch it become OR. Then open the **Theory** tab for why.': "AND hazır ayarından **yalnızca bias'ı** −0.5'e doğru sürükle ve OR'a dönüşmesini izle. Nedenini öğrenmek için **Teori** sekmesini aç.",
    'Why these gates (AND, OR, XOR …)?': 'Neden bu kapılar (AND, OR, XOR …)?',
    'Logic gates are the **smallest, exact tests** of what one neuron can do — 4 points and a visible decision line.\n\n- **AND / OR / NAND / NOR** are *linearly separable* → a single neuron **can** do them.\n- **XOR / XNOR** are *not* separable → **no single neuron can** (with any weights). That failure is exactly why we need **hidden layers** (Tier 1).\n\nFull story in the **Theory** tab, §9.': 'Mantık kapıları, bir nöronun ne yapabileceğinin **en küçük, kesin testleridir** — 4 nokta ve görünür bir karar çizgisi.\n\n- **AND / OR / NAND / NOR** *lineer olarak ayrılabilir* → tek bir nöron bunları **yapabilir**.\n- **XOR / XNOR** ayrılabilir *değil* → **hiçbir tek nöron yapamaz** (herhangi bir ağırlıkla). Bu başarısızlık tam olarak neden **gizli katmanlara** ihtiyaç duyduğumuzdur (Tier 1).\n\nTam hikâye **Teori** sekmesinde, §9.',
    'Preset': 'Hazır ayar',
    'Post-training — from base LM to assistant': "Post-training — base LM'den asistana",
    'A from-scratch GPT only continues text. SFT + preference tuning (RLHF / DPO), done cheaply with LoRA, turn it into a helpful assistant. (Concepts + diagrams.)': 'Sıfırdan bir GPT yalnızca metni devam ettirir. SFT + tercih ayarı (RLHF / DPO), LoRA ile ucuza yapıldığında, onu yardımcı bir asistana dönüştürür. (Kavramlar + diyagramlar.)',
    'Regularization — taming overfitting': "Regularizasyon — overfitting'i evcilleştirmek",
    'Dial L2 weight decay up and down on a noisy dataset: watch the boundary go from wiggly to smooth and the train/test gap close at the sweet spot.': "Gürültülü bir veri kümesinde L2 weight decay'i aşağı yukarı ayarla: sınırın dalgalıdan pürüzsüze geçişini ve train/test farkının en uygun noktada nasıl kapandığını izle.",
    '🎚 Tune it': '🎚 Ayarla',
    'A high-capacity MLP `(40, 40)` on **noisy two-moons**. Move the regularization strength **λ** and watch the boundary and the train/test gap:': "**Gürültülü two-moons** üzerinde yüksek kapasiteli bir MLP `(40, 40)`. Regularizasyon gücü **λ**'yı oynat ve sınırı ile train/test farkını izle:",
    'train − test gap': 'train − test farkı',
    'L2 makes large weights costly → smaller weights → a smoother boundary. Too little λ overfits (left of the green line), too much underfits (right). The green dashed line is the validation-best λ; grey dotted is your current pick.': "L2, büyük ağırlıkları maliyetli yapar → daha küçük ağırlıklar → daha pürüzsüz bir sınır. Çok az λ overfit eder (yeşil çizginin solu), çok fazlası underfit eder (sağ). Yeşil kesikli çizgi validation'a göre en iyi λ; gri noktalı çizgi senin mevcut seçimin.",
    'Decision boundary at this λ': "Bu λ'daki karar sınırı",
    'Accuracy vs λ — the sweet spot': 'Doğruluğa karşı λ — en uygun nokta',
    'RNN — recurrent networks for sequences': 'RNN — diziler için recurrent ağlar',
    'Walk a sequence carrying a hidden state. The Live tab runs a 1-unit RNN so you can watch the recurrent weight set how long it remembers.': 'Bir gizli durum (hidden state) taşıyarak bir dizide ilerle. Canlı sekmesi 1 birimlik bir RNN çalıştırır; böylece recurrent ağırlığın ne kadar süre hatırladığını nasıl belirlediğini izleyebilirsin.',
    '🔁 Hidden state': '🔁 Gizli durum',
    'A one-unit RNN: $h_t = \\tanh(w_x\\,x_t + w_h\\,h_{t-1})$. Pick an input sequence and tune the weights — watch the **hidden state** (memory) evolve:': 'Tek birimlik bir RNN: $h_t = \\tanh(w_x\\,x_t + w_h\\,h_{t-1})$. Bir girdi dizisi seç ve ağırlıkları ayarla — **gizli durumun** (bellek) nasıl evrildiğini izle:',
    'input sequence': 'girdi dizisi',
    'input weight wₓ': 'girdi ağırlığı wₓ',
    'recurrent weight wₕ (memory)': 'recurrent ağırlık wₕ (bellek)',
    'The recurrent weight wₕ is the **memory knob**: small forgets fast, ≈1 remembers long, >1 blows up. The same wₕ multiplies the gradient at every step too — which is exactly why long sequences vanish/explode, and why LSTMs add gates.': "Recurrent ağırlık wₕ **bellek düğmesidir**: küçük olan çabuk unutur, ≈1 uzun süre hatırlar, >1 patlar. Aynı wₕ her adımda gradyanı da çarpar — uzun dizilerin tam da bu yüzden kaybolması/patlaması ve LSTM'lerin neden kapı (gate) eklediğidir.",
    'impulse remembered for ≈': 'impuls şu kadar hatırlandı ≈',
    'Decoding — how an LLM picks the next token': "Decoding — bir LLM bir sonraki token'ı nasıl seçer",
    'One fixed next-token distribution, four strategies. Watch greedy / temperature / top-k / top-p reshape it and sample — the dial between reliable and creative.': "Tek bir sabit sonraki-token dağılımı, dört strateji. greedy / temperature / top-k / top-p'nin onu nasıl yeniden şekillendirip örneklediğini izle — güvenilir ile yaratıcı arasındaki ayar düğmesi.",
    '🎲 Compare': '🎲 Karşılaştır',
    "The model's next-token distribution after **“The cat sat on the ___”**. Pick a decoding strategy and see which tokens survive and what gets sampled:": "Modelin **“The cat sat on the ___”** sonrasındaki sonraki-token dağılımı. Bir decoding stratejisi seç ve hangi token'ların hayatta kaldığını ve neyin örneklendiğini gör:",
    'strategy': 'strateji',
    'temperature': 'temperature',
    'k (top-k)': 'k (top-k)',
    'p (top-p)': 'p (top-p)',
    'candidates kept': 'tutulan adaylar',
    'top candidate': 'en iyi aday',
    'most-likely P': 'en olası P',
    'Sample 200 tokens ▶': '200 token örnekle ▶',
    'Decoding is a generation-time choice, not part of the model. Temperature reshapes the whole distribution; top-k / top-p **cut the tail** before sampling. Same model, very different text.': 'Decoding, modelin parçası değil, üretim anına ait bir seçimdir. Temperature tüm dağılımı yeniden şekillendirir; top-k / top-p örneklemeden önce **kuyruğu keser**. Aynı model, çok farklı metin.',
    'Greedy always returns the same token — zero diversity.': "Greedy her zaman aynı token'ı döndürür — sıfır çeşitlilik.",
    '🐍 Sandbox': '🐍 Sandbox',
    "A scratchpad with numpy and the lab's `core` preloaded. Test exercises, experiment, and plot — without leaving the app. Variables persist across runs (like a notebook).": "numpy ve laboratuvarın `core`'u önceden yüklü bir karalama defteri. Uygulamadan çıkmadan alıştırmaları test et, deney yap ve grafik çiz. Değişkenler çalıştırmalar arasında korunur (bir notebook gibi).",
    'example': 'örnek',
    'Load': 'Yükle',
    'Safe run': 'Güvenli çalıştır',
    'timeout (s)': 'zaman aşımı (s)',
    'code': 'kod',
    'Run': 'Çalıştır',
    'Reset namespace': "Namespace'i sıfırla",
    '**Output**': '**Çıktı**',
    'How it works / tips': 'Nasıl çalışır / ipuçları',
    "- **numpy** is preloaded as `np`; the lab's building blocks import normally, e.g. `from core.neuron import Neuron`.\n- **Variables persist** across runs (notebook-style). Use **Reset namespace** to start clean.\n- **Plots** appear inline — just create a matplotlib figure (no need for `plt.show()`).\n- **Safe run** executes in a separate process with a timeout (no inline plots / no persistence) — use it if you're worried about an infinite loop freezing the app.\n- Runs in the lab's venv from the `ai-lab/` directory, so relative paths and `pytest` work.": "- **numpy** `np` olarak önceden yüklüdür; laboratuvarın yapı taşları normal şekilde import edilir, örn. `from core.neuron import Neuron`.\n- **Değişkenler** çalıştırmalar arasında korunur (notebook tarzı). Temiz başlamak için **Namespace'i sıfırla**'yı kullan.\n- **Grafikler** satır içinde görünür — sadece bir matplotlib figürü oluştur (`plt.show()` gerekmez).\n- **Güvenli çalıştır**, zaman aşımı olan ayrı bir süreçte çalışır (satır içi grafik yok / kalıcılık yok) — sonsuz bir döngünün uygulamayı dondurmasından endişeliysen bunu kullan.\n- Laboratuvarın venv'inde, `ai-lab/` dizininden çalışır; böylece göreli yollar ve `pytest` çalışır.",
    '(ran fine — no output. Use print(...) or plt.plot(...) to see something.)': '(sorunsuz çalıştı — çıktı yok. Bir şey görmek için print(...) veya plt.plot(...) kullan.)',
    '🧭 The big picture — from one neuron to computing': '🧭 Büyük resim — tek nörondan hesaplamaya',
    'A 5-minute map of the whole lab: what a neural network is, and how a single neuron scales all the way to a GPT.': "Tüm laboratuvarın 5 dakikalık haritası: bir sinir ağının ne olduğu ve tek bir nöronun ta GPT'ye kadar nasıl ölçeklendiği.",
    '**One idea scales to all of it.** A neuron is a tiny decision-maker: multiply each input by a *weight*, add them up, and bend the result with a simple curve. Wire a few together and they do **logic and arithmetic**. Stack and *train* them and they recognise images, translate languages, and — at billions strong — **write text**. This page is the map; the sidebar is the journey.': '**Tek bir fikir hepsine ölçeklenir.** Bir nöron küçük bir karar vericidir: her girdiyi bir *ağırlıkla* çarp, topla ve sonucu basit bir eğriyle bük. Birkaçını birbirine bağla; **mantık ve aritmetik** yaparlar. Üst üste diz ve *eğit*; görüntüleri tanır, dilleri çevirir ve — milyarlarcası bir araya gelince — **metin yazarlar**. Bu sayfa harita; sidebar ise yolculuk.',
    'Where you are: stops **1–6 are all built and runnable** — a single neuron, an MLP that learns XOR live, attention, a tiny GPT, and a real PyTorch nanoGPT (e21). Everything on this map is something you can open and play with.': "Neredesin: **1–6 durakları hepsi kurulu ve çalıştırılabilir** — tek bir nöron, XOR'u canlı öğrenen bir MLP, attention, küçük bir GPT ve gerçek bir PyTorch nanoGPT (e21). Bu haritadaki her şey açıp oynayabileceğin bir şey.",
    '#### 🧩 What is a neural network? (in 60 seconds)': '#### 🧩 Sinir ağı nedir? (60 saniyede)',
    'A **neural network** is just **many neurons wired together and tuned by data**. Each neuron does the same little thing:': 'Bir **sinir ağı** sadece **birbirine bağlı ve veriyle ayarlanmış birçok nörondur**. Her nöron aynı küçük şeyi yapar:',
    '#### 🪜 The chain, stop by stop': '#### 🪜 Zincir, durak durak',
    'Each stop is a page in this lab — click to open it.': 'Her durak bu laboratuvarda bir sayfadır — açmak için tıkla.',
    "#### 🔁 It's the same operation — just bigger": '#### 🔁 Aynı işlem — sadece daha büyük',
    'Nothing fundamentally new happens as you go right along the chain. Every box is a **weighted sum (a matrix multiply) followed by a nonlinearity** — exactly what runs on a GPU. **Depth** means doing it many times, each layer composing richer features from the last; **scale** means doing it *a lot*.': "Zincir boyunca sağa gittikçe temelde yeni bir şey olmaz. Her kutu, **bir ağırlıklı toplam (matris çarpımı) ardından bir nonlinearity**'dir — tam olarak bir GPU'da çalışan şey. **Derinlik**, bunu birçok kez yapmak demektir; her katman bir öncekinden daha zengin feature'lar kurar; **ölçek** ise bunu *çok* yapmak demektir.",
    "Same unit, repeated — from 1 neuron, to a layer, to ~100 billion in a frontier LLM. And like a brain it's **robust**: no single weight is critical, because every decision rests on a sum of many.": "Aynı birim, tekrarlanıyor — 1 nörondan bir katmana, oradan en uçtaki bir LLM'de ~100 milyara. Ve bir beyin gibi **dayanıklıdır**: hiçbir tek ağırlık kritik değildir, çünkü her karar birçoğunun toplamına dayanır.",
    '#### 🔭 Two views that meet': '#### 🔭 Buluşan iki bakış açısı',
    "- **Logic view:** neuron → gate → **circuit** → (with memory) a **universal computer**. NAND-completeness makes this exact — see *Neurons → computer*.\n- **Function view:** neuron → linear model → **MLP** → fits **any function** → specialised to images and text.\n\nA **trained network is both at once** — soft, *learned* logic gates **and** a function approximator. The 'learning' is just gradient descent (Math **X4**) finding the weights, and backprop (Math **X2**) supplying the gradients.": "- **Mantık bakışı:** nöron → kapı → **devre** → (bellekle) bir **evrensel bilgisayar**. NAND-tamlığı bunu kesinleştirir — bkz. *Nöronlar → bilgisayar*.\n- **Fonksiyon bakışı:** nöron → lineer model → **MLP** → **herhangi bir fonksiyonu** uydurur → görüntü ve metne özelleşir.\n\n**Eğitilmiş bir ağ aynı anda ikisidir** — yumuşak, *öğrenilmiş* mantık kapıları **ve** bir fonksiyon yaklaştırıcısı. 'Öğrenme' sadece ağırlıkları bulan gradient descent (Math **X4**) ve gradyanları sağlayan backprop'tur (Math **X2**).",
    "#### 🌍 Where it shows up — it's all the same recipe": '#### 🌍 Nerede karşına çıkıyor — hepsi aynı tarif',
    "| Application | the network maps… |\n|---|---|\n| Spam filter | email words → *spam?* |\n| Image recognition | pixels → *'cat'* |\n| Recommendations | your history → *what's next* |\n| Translation | English → French |\n| Chatbot / LLM | the text so far → *the next word* |\n\nDifferent data, same machine: numbers in → weighted sums + nonlinearities → numbers out, with the weights **learned from examples**.": "| Uygulama | ağ neyi eşler… |\n|---|---|\n| Spam filtresi | e-posta kelimeleri → *spam mı?* |\n| Görüntü tanıma | pikseller → *'kedi'* |\n| Öneriler | geçmişin → *sırada ne var* |\n| Çeviri | İngilizce → Fransızca |\n| Chatbot / LLM | şimdiye kadarki metin → *bir sonraki kelime* |\n\nFarklı veri, aynı makine: sayılar girer → ağırlıklı toplamlar + nonlinearity'ler → sayılar çıkar; ağırlıklar **örneklerden öğrenilir**.",
    '#### 🚩 Start the journey': '#### 🚩 Yolculuğa başla',
    'Follow the five levels in the sidebar, or jump in here:': "Sidebar'daki beş seviyeyi izle ya da buradan dal:",
    '| term | in plain words |\n|---|---|\n| **Neuron** | weights × inputs, summed, then a curve → one number |\n| **Weight** | how much an input matters *(learned)* |\n| **Bias** | a baseline / threshold *(learned)* |\n| **Activation** | the curve (ReLU, sigmoid…) that lets it bend |\n| **Layer** | many neurons working in parallel |\n| **Network** | layers stacked — each builds on the last |\n| **Training** | nudging every weight to reduce error |': '| terim | sade anlatımıyla |\n|---|---|\n| **Nöron** | ağırlıklar × girdiler, toplanır, sonra bir eğri → tek bir sayı |\n| **Ağırlık (weight)** | bir girdinin ne kadar önemli olduğu *(öğrenilir)* |\n| **Bias** | bir taban değer / eşik *(öğrenilir)* |\n| **Aktivasyon** | bükmeyi sağlayan eğri (ReLU, sigmoid…) |\n| **Katman (layer)** | paralel çalışan birçok nöron |\n| **Ağ (network)** | üst üste dizilmiş katmanlar — her biri bir öncekine dayanır |\n| **Eğitim** | hatayı azaltmak için her ağırlığı azar azar itmek |',
    '**The only operation, repeated:** a **weighted sum → a nonlinearity**. Do it once = a neuron. Do it in parallel = a layer. Do it deep = a network. Do it billions of times = an LLM.\n\n**Learning** = *backprop* finds how to change each weight, an *optimizer* takes the step (Levels 2 & the Math track).': '**Tek bir işlem, tekrarlanır:** bir **ağırlıklı toplam → bir nonlinearity**. Bir kez yap = bir nöron. Paralel yap = bir katman. Derin yap = bir ağ. Milyarlarca kez yap = bir LLM.\n\n**Öğrenme** = *backprop* her ağırlığın nasıl değişeceğini bulur, bir *optimizer* adımı atar (Seviye 2 ve Math kanalı).',
    'Tokenization — how text becomes tokens': "Tokenizasyon — metin nasıl token'a dönüşür",
    'Before any LLM math, text is cut into tokens. Compare character / word / sub-word, and train a tiny BPE tokenizer live by merging frequent pairs.': "Herhangi bir LLM matematiğinden önce metin token'lara bölünür. Karakter / kelime / alt-kelime'yi karşılaştır ve sık çiftleri birleştirerek küçük bir BPE tokenizer'ı canlı eğit.",
    '✂️ Tokenize': '✂️ Tokenize et',
    'text to tokenize': 'tokenize edilecek metin',
    'BPE merges (vocabulary granularity)': 'BPE birleştirmeleri (sözlük ayrıntı düzeyi)',
    'characters': 'karakterler',
    'words': 'kelimeler',
    'BPE tokens': "BPE token'ları",
    'merges learned': 'öğrenilen birleştirmeler',
    'Your text as BPE tokens:': "BPE token'ları olarak metnin:",
    'Same text, different granularity: more merges → fewer, longer tokens (shorter sequence) but a bigger vocabulary. Real LLMs pick a fixed vocab (~30k–100k) — the balance point. Unknown words just fall back to smaller pieces, so no OOV.': "Aynı metin, farklı ayrıntı düzeyi: daha çok birleştirme → daha az, daha uzun token (daha kısa dizi) ama daha büyük bir sözlük. Gerçek LLM'ler sabit bir sözlük seçer (~30k–100k) — denge noktası. Bilinmeyen kelimeler sadece daha küçük parçalara düşer, yani OOV yok.",
    'First learned merges (most frequent pairs, in order):': 'İlk öğrenilen birleştirmeler (en sık çiftler, sırayla):',
    'Tiny GPT — Transformer & next-token prediction': 'Küçük GPT — Transformer ve sonraki-token tahmini',
    'Wrap attention in a block, stack it, and train on one objective: predict the next token. The Live tab trains a tiny char-level LM you can prompt and sample.': "Attention'ı bir blokta sar, üst üste diz ve tek bir hedefte eğit: bir sonraki token'ı tahmin et. Canlı sekmesi, prompt verip örnekleyebileceğin küçük bir karakter düzeyinde LM eğitir.",
    '⌨ Generate': '⌨ Üret',
    'A tiny **character-level** language model trained on a few sentences — it predicts the **next character** from the last few. Real GPTs replace the fixed window with stacked attention, but the next-token softmax + sampling are the same.': "Birkaç cümle üzerinde eğitilmiş küçük bir **karakter düzeyinde** dil modeli — son birkaç karakterden **bir sonraki karakteri** tahmin eder. Gerçek GPT'ler sabit pencereyi üst üste dizili attention ile değiştirir, ama sonraki-token softmax'ı + örnekleme aynıdır.",
    'prompt': 'prompt',
    'characters to generate': 'üretilecek karakter sayısı',
    'Generate ▶': 'Üret ▶',
    "One objective — next-token prediction via softmax + cross-entropy — and generation is just sampling that softmax, token by token. Scale this up and it's a GPT.": "Tek bir hedef — softmax + cross-entropy ile sonraki-token tahmini — ve üretim, o softmax'ı token token örneklemekten ibarettir. Bunu ölçekle, bir GPT olur.",
    '⚡ The **real, GPU-trained** version is experiment **e21** — a PyTorch Transformer (causal multi-head attention + AdamW) at `experiments/tier4_attention/e21_nanogpt`. Run it from the **Experiments** page or the CLI (`--download --iters 3000` for Shakespeare).': "⚡ **Gerçek, GPU ile eğitilen** versiyon **e21** deneyidir — `experiments/tier4_attention/e21_nanogpt` konumunda bir PyTorch Transformer (causal multi-head attention + AdamW). **Deneyler** sayfasından ya da CLI'dan çalıştır (Shakespeare için `--download --iters 3000`).",
    'training corpus (what it learned from)': "eğitim corpus'u (neyden öğrendiği)",
    'Two neurons — playground': 'İki nöron — oyun alanı',
    'How two neurons connect, and why that beats one. Toggle the wiring below.': 'İki nöronun nasıl bağlandığı ve bunun neden tek nörondan üstün olduğu. Aşağıdaki kabloyu (wiring) değiştir.',
    '**Two neurons, same inputs, no link** — each draws its own line; together they cut the plane into up to **4 regions** and give every point a 2-bit code (A, B). This is exactly a hidden *layer* of width 2.': "**İki nöron, aynı girdiler, bağlantı yok** — her biri kendi çizgisini çizer; birlikte düzlemi en fazla **4 bölgeye** ayırır ve her noktaya 2 bit'lik bir kod (A, B) verir. Bu tam olarak genişliği 2 olan gizli bir *katmandır*.",
    "Two parallel neurons **transform** the input into a richer 2-D code, but can't yet make a single decision — something must combine A and B. That's the next wiring →": "İki paralel nöron girdiyi daha zengin bir 2 boyutlu koda **dönüştürür**, ama henüz tek bir karar veremez — bir şeyin A ve B'yi birleştirmesi gerekir. Sıradaki kablo bağlantısı bu →",
    '**Hidden → output (with a skip).** Neuron *h* builds a feature; the output neuron *y* sees **the inputs and h**. With the defaults below, two neurons compute **XOR** — what one neuron never can (e03).': "**Gizli → çıktı (bir skip ile).** Nöron *h* bir feature kurar; çıktı nöronu *y* **girdileri ve h'yi** görür. Aşağıdaki varsayılanlarla iki nöron **XOR** hesaplar — tek bir nöronun asla yapamayacağı şey (e03).",
    'The hidden **AND**-neuron fires only at (1,1); the output is basically **OR**, but `u = −2` lets h **veto** that corner → XOR. The hidden unit invents the feature that makes the problem linearly separable for the next neuron — the essence of hidden layers.': "Gizli **AND** nöronu yalnızca (1,1)'de ateşlenir; çıktı temelde **OR**'dur, ama `u = −2` h'nin o köşeyi **veto** etmesini sağlar → XOR. Gizli birim, problemi bir sonraki nöron için lineer ayrılabilir yapan feature'ı icat eder — gizli katmanların özü.",
    'Wiring': 'Kablo bağlantısı (wiring)',
    '**Neuron A** (coral line)': '**Nöron A** (mercan çizgi)',
    'wₐ₀': 'wₐ₀',
    'wₐ₁': 'wₐ₁',
    'bₐ': 'bₐ',
    '**Neuron B** (blue line)': '**Nöron B** (mavi çizgi)',
    'w_b₀': 'w_b₀',
    'w_b₁': 'w_b₁',
    'b_b': 'b_b',
    '**Hidden neuron h** = step(w·x + b)  *(default = AND)*': '**Gizli nöron h** = step(w·x + b)  *(varsayılan = AND)*',
    'w_h₀': 'w_h₀',
    'w_h₁': 'w_h₁',
    'b_h': 'b_h',
    '**Output y** = step(v₀x₀ + v₁x₁ + u·h + c)': '**Çıktı y** = step(v₀x₀ + v₁x₁ + u·h + c)',
    'v₀': 'v₀',
    'v₁': 'v₁',
    'u  (weight on h)': 'u  (h üzerindeki ağırlık)',
    'c  (bias)': 'c  (bias)',
}
